// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_EMBER_AF_COMMAND_PARSE_HEADER
#define SILABS_EMBER_AF_COMMAND_PARSE_HEADER


// This is a set of generated prototype for functions that parse the
// the incomming message, and call appropriate command handler.

// Cluster: Basic, server
EmberAfStatus emberAfBasicClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Identify, server
EmberAfStatus emberAfIdentifyClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Groups, server
EmberAfStatus emberAfGroupsClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Scenes, server
EmberAfStatus emberAfScenesClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: On/off, server
EmberAfStatus emberAfOnOffClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Level Control, server
EmberAfStatus emberAfLevelControlClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Alarms, server
EmberAfStatus emberAfAlarmClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Commissioning, server
EmberAfStatus emberAfCommissioningClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Color Control, server
EmberAfStatus emberAfColorControlClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Encelium Interface Cluster, server
EmberAfStatus emberAfEnceliumInterfaceClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Encelium Diagnostics, client
EmberAfStatus emberAfEnceliumDiagnosticsClusterClientCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Encelium Diagnostics, server
EmberAfStatus emberAfEnceliumDiagnosticsClusterServerCommandParse(EmberAfClusterCommand *cmd);

// Cluster: Encelium Emergency Cluster, server
EmberAfStatus emberAfEnceliumEmergencyClusterServerCommandParse(EmberAfClusterCommand *cmd);

#endif // SILABS_EMBER_AF_COMMAND_PARSE_HEADER
