// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "../../../../../SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/util/tokens.h"

// Token header for the Encelium Commissioning v2 plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/plugin/encelium-commissioning/encelium-commissioning-tokens.h"

// Token header for the Scenes Server Cluster plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/plugin/scenes/scenes-tokens.h"

// Token header for the Reporting plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/plugin/reporting/reporting-tokens.h"

// Token header for the OsramDS Reset2Factory plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v5/developer/sdks/gecko_sdk_suite/v3.2/protocol/zigbee/app/framework/plugin/osramds-reset2factory/Reset2Factory-Tokens.h"

// Custom token header file
#include "app-tokens-def.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

