// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "af.h"

// Init function declarations.
void emberAfMainInitCallback(void);  // Global
void emberAfInit(void);  // Global

void emAfInit(void)
{
  emberAfMainInitCallback();  // Global
  emberAfInit();  // Global
}

// Tick function declarations.
void emberAfMainTickCallback(void);  // Global
void emberAfTick(void);  // Global

void emAfTick(void)
{
  emberAfMainTickCallback();  // Global
  emberAfTick();  // Global
}

// Marker function declarations.
void emberAfMarkBuffersCallback(void);  // Global

void emAfMarkBuffers(void)
{
  emberAfMarkBuffersCallback();  // Global
}

void emAfResetAttributes(uint8_t endpointId)
{
}

// PreCommandReceived function declarations.
bool emberAfPreCommandReceivedCallback(EmberAfClusterCommand* cmd);  // Global
bool emAfPluginEnceliumCommissioningPreCommandReceivedCallback(EmberAfClusterCommand* cmd);  // Plugin: encelium-commissioning

bool emAfPreCommandReceived(EmberAfClusterCommand* cmd)
{
  return (emberAfPreCommandReceivedCallback(cmd)  /* Global */
          || emAfPluginEnceliumCommissioningPreCommandReceivedCallback(cmd)  /* Plugin: encelium-commissioning */);
}

// PreZDOMessageReceived function declarations.
bool emberAfPreZDOMessageReceivedCallback(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);  // Global
bool emberAfPluginEnceliumCommissioningPreZDOMessageReceivedCallback(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);  // Plugin: encelium-commissioning

bool emAfPreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length)
{
  return (emberAfPreZDOMessageReceivedCallback(emberNodeId, apsFrame, message, length)  /* Global */
          || emberAfPluginEnceliumCommissioningPreZDOMessageReceivedCallback(emberNodeId, apsFrame, message, length)  /* Plugin: encelium-commissioning */);
}

bool emAfRetrieveAttributeAndCraftResponse(uint8_t endpoint, EmberAfClusterId clusterId, EmberAfAttributeId attrId, uint8_t mask, uint16_t maunfacturerCode, uint16_t readLength)
{
  return 0; // false
}

// ZigbeeKeyEstablishment function declarations.
void emberAfZigbeeKeyEstablishmentCallback(EmberEUI64 partner, EmberKeyStatus status);  // Global

void emAfZigbeeKeyEstablishment(EmberEUI64 partner, EmberKeyStatus status)
{
  emberAfZigbeeKeyEstablishmentCallback(partner, status);  // Global
}

// ReadAttributesResponse function declarations.
bool emberAfReadAttributesResponseCallback(EmberAfClusterId clusterId,uint8_t* buffer,uint16_t bufLen);  // Global

bool emAfReadAttributesResponse(EmberAfClusterId clusterId,uint8_t* buffer,uint16_t bufLen)
{
  return emberAfReadAttributesResponseCallback(clusterId, buffer, bufLen);  // Global
}

// ReportAttributes function declarations.
bool emberAfReportAttributesCallback(EmberAfClusterId clusterId,uint8_t * buffer,uint16_t bufLen);  // Global

bool emAfReportAttributes(EmberAfClusterId clusterId,uint8_t * buffer,uint16_t bufLen)
{
  return emberAfReportAttributesCallback(clusterId, buffer, bufLen);  // Global
}
